name: my-app1

on: push

jobs:
  build:
    runs-on : windows-latest

    steps:
    - name : my checkout
      uses: actions/checkout@v4
    - name: use node.js
      uses: actions/setup-node@v4
      with :
        node-version: latest
    - run : npm install
    - run : npm build
      
